import "./globals.css";
import Navbar from "./components/Navbar/index";
import Footer from "./components/Footer/index";
import WhatsappIcon from "./components/whatsapp";

export const metadata = {
  title: "Paidin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <WhatsappIcon />

        {children}
        <Footer />
      </body>
    </html>
  );
}
